sudo: required
services:
  - docker

before_install:
  - docker build -t nigelfrnds/docker-react-test -f Dockerfile.dev .

script:
  - docker run -e CI=true nigelfrnds/docker-react-test npm run test